echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27 and learning DevOps"
echo "I am working in REQ092348"
echo "I have learnt Github and Git"
echo "Hi there, I am Sagar and I am performing my first practical of github and git"
echo "Hello, I am Shyam and now I am using git bash to commit my changes"
echo "this is my branch practical of github and git"
